export enum CollaborationEvents {
  JOIN_ROOM = "JOIN_ROOM",
  LEAVE_ROOM = "LEAVE_ROOM",
  UPDATE_CODE = "UPDATE_CODE",
  // REQUEST_ROOM_STATE = "REQUEST_ROOM_STATE",
  SEND_MESSAGE = "SEND_MESSAGE",
  REQUEST_CHAT_STATE = "REQUEST_CHAT_STATE",
  NEXT_QUESTION = "NEXT_QUESTION",
  CALL = "CALL",
  ACCEPT_CALL = "ACCEPT_CALL",
  END_CALL = "END_CALL",
}
