export enum CollaborationEvents {
  JOIN_ROOM = "JOIN_ROOM",
  LEAVE_ROOM = "LEAVE_ROOM",
  UPDATE_CODE = "UPDATE_CODE",
  // REQUEST_ROOM_STATE = "REQUEST_ROOM_STATE",
  SEND_MESSAGE = "SEND_MESSAGE",
  REQUEST_NEW_CHATS = "REQUEST_NEW_CHATS",
}
