steps:
  # Build the question-service
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/question-service:$COMMIT_SHA"
      - "-f"
      - "./question_service/Dockerfile.prod"
      - "./question_service"

  # Push the image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/question-service:$COMMIT_SHA"

  # Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "question-service"
      - "--image"
      - "gcr.io/$PROJECT_ID/question-service:$COMMIT_SHA"
      - "--region"
      - "us-west2"
      - "--platform"
      - "managed"
      - "--port"
      - "8080"
      - "--allow-unauthenticated"
      - "--set-secrets"
      - "MONGODB_URI=MONGODB_URI:latest"

  # user service
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/user-service:$COMMIT_SHA"
      - "-f"
      - "./users_service/Dockerfile.prod"
      - "./users_service"

  # Push the image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/user-service:$COMMIT_SHA"

  # Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "user-service"
      - "--image"
      - "gcr.io/$PROJECT_ID/user-service:$COMMIT_SHA"
      - "--region"
      - "us-west2"
      - "--platform"
      - "managed"
      - "--port"
      - "8080"
      - "--allow-unauthenticated"
      - "--set-secrets"
      - "MONGODB_URI=MONGODB_URI:latest"
images:
  - "gcr.io/$PROJECT_ID/question-service:$COMMIT_SHA"
  - "gcr.io/$PROJECT_ID/user-service:$COMMIT_SHA"
