version: "3"

services:
    question-service:
        build:
            context: ./question_service
        environment:
            - MONGODB_URI=${MONGODB_URI}
            - PORT=${PORT}
        ports:
            - 5001:5001
