version: "3"

services:
    user-service:
        build:
            context: ./users_service
        environment:
            - MONGODB_URI=${MONGODB_URI}
            - USER_SERVICE_PORT=${USER_SERVICE_PORT}
            - JWT_SECRET=${JWT_SECRET}
        ports:
            - "5001:5001"
    question-service:
        build:
            context: ./question_service
        environment:
            - MONGODB_URI=${MONGODB_URI}
            - QUESTION_SERVICE_PORT=${QUESTION_SERVICE_PORT}
        ports:
            - "5002:5002"
