version: "3"

services:
  frontend:
    build:
      context: ./peerprep_fe
    volumes:
      - ./peerprep_fe:/app
      - /app/node_modules
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT}
      - API_GATEWAY_PORT=${API_GATEWAY_PORT}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"

  gateway_service:
    build:
      context: ./gateway_service
    environment:
      - API_GATEWAY_PORT=${API_GATEWAY_PORT}
      - USER_SERVICE_PORT=${USER_SERVICE_PORT}
      - QUESTION_SERVICE_PORT=${QUESTION_SERVICE_PORT}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - ${API_GATEWAY_PORT}:${API_GATEWAY_PORT}

  user-service:
    build:
      context: ./users_service
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - USER_SERVICE_PORT=${USER_SERVICE_PORT}
    ports:
      - "5001:5001"

  question-service:
    build:
      context: ./question_service
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - QUESTION_SERVICE_PORT=${QUESTION_SERVICE_PORT}
    ports:
      - "5002:5002"

  collab-service:
    build:
      context: ./collab_service
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - COLLLAB_SERVICE_PORT=${COLLLAB_SERVICE_PORT}
    ports:
      - "${COLLLAB_SERVICE_PORT}:${COLLLAB_SERVICE_PORT}"

  matching_service:
    build:
      context: ./matching_service
    environment:
      - MATCHING_SERVICE_PORT=${MATCHING_SERVICE_PORT}
      - USER_SERVICE_PORT=${USER_SERVICE_PORT}
      - QUESTION_SERVICE_PORT=${QUESTION_SERVICE_PORT}
    ports:
      - "5004:5004"

  events_service:
    image: apache/kafka:latest
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker, controller
      KAFKA_LISTENERS: PLAINTEXT://${KAFKA_BROKER_ROUTE}:${KAFKA_BROKER_PORT},CONTROLLER://${KAFKA_BROKER_ROUTE}:${KAFKA_CONTROLLER_PORT}
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${KAFKA_BROKER_ROUTE}:${KAFKA_BROKER_PORT}
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@${KAFKA_BROKER_ROUTE}:${KAFKA_CONTROLLER_PORT}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: ${KAFKA_NUM_PARTITIONS}
